import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-home',
  standalone: true,
  template: `
    <div class="h-full flex flex-col items-center justify-center px-6 text-center">

      <h1 class="text-5xl font-bold text-gray-900 mb-4">Welcome to RusticAI</h1>
      <p class="text-xl text-gray-500 max-w-xl mb-10">
        This is a demonstration application built on <span class="font-medium text-primary-600">Rustic AI</span> —
        an open-source multi-agent framework built on <span class="font-medium text-primary-600">Rust</span>. Explore the Chats and Agents sections to interact
        with LLM-powered conversations and agentic workflows.
      </p>

      <p class="text-base text-gray-400 max-w-lg">
        <span class="font-medium">Disclaimer:</span>
        This is a demo application intended for evaluation and development purposes only.
        Responses are generated by AI models and may be inaccurate, incomplete, or misleading.
        Do not rely on outputs for financial, legal, medical, or other critical decisions.
      </p>

    </div>
  `
})
export default class HomeComponent {}
